# Site settings
title: BEM Library
email: waikitkan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A BEM library
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://waikitkan.github.io/bem-library/" # the base hostname & protocol for your site
twitter_username: waikitkan
github_username:  waikitkan

# Build settings
markdown: kramdown